---
title: "run_analysis"
author: "RobertoAtRL"
date: "17 dicembre 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#import data
```{r import data}
print("Hello, this is my version")
print(version)
yourdirectory<-"H:\\CasaUfficio\\R notes\\JH Coursera Data Science Toolbox\\Getting and Cleaning Data"
#create dir
setwd("H:\\CasaUfficio\\R notes\\JH Coursera Data Science Toolbox\\Getting and Cleaning Data")
if(!file.exists("data")) {
  dir.create("data")
}
setwd(".\\data")
url<-"https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
if(!file.exists("data.zip")) {
  download.file(url,destfile="data.zip")
  dateDownloaded<-date()
  print(dateDownloaded)
}

mydir<-getwd()
print(mydir)
if(!file.exists("UCI HAR Dataset")) {
  unzip("data.zip", exdir=mydir)  
}
fileslist<-list.files(path=mydir,pattern="*.txt", full.names=TRUE, recursive=TRUE)

#read triaxial data into a list "hte"
for (h in 1:2){
    for (i in 1:3){
    for (j in 1:3){
      a<-c("body_acc","body_gyro","total_acc")[i]
      b<-c("_x_","_y_","_z_")[j]
      c<-traintest[h]
      if (h==1 & i==1 & j==1) {
        hte<-list(read.table(fileslist[grepl(paste(a,b,c,".txt",sep=""),fileslist)],sep=""))
              }else {
          hte[[length(hte)+1]]<-read.table(fileslist[grepl(paste(a,b,c,".txt",sep=""),fileslist)],sep="")                }
      names(hte)[length(hte)]<-paste(a,b,c,sep="")
      print(names(hte)[length(hte)])
    }
  }  
}
#read train and test data into the same list "hte"
for (i in c("X_","/y_","subject_")) {
  for (j in traintest) {
    hte[[length(hte)+1]]<-read.table(fileslist[grepl(paste(i,j,sep=""),fileslist)],sep="")
    names(hte)[length(hte)]<-paste(i,j,sep="")
  }
}
names(hte)

```

## A function to add the column that distinguishes between train and test

```{A function, echo=FALSE}
addtraintest<-function(x,z) {
  traintest<-rep(z,nrow(x))
  x1<-cbind(x,traintest)    
  return(x1)
  }

```


## Apply function to create column that distinguishes between train and test set

```{r traintest, echo=FALSE}
for (i in c("test","train")) {
  if (i=="test") {
    htetest<-lapply(hte[grepl(i,names(hte))],addtraintest,z=i)
    names(htetest)<-names(hte)[grepl(i,names(hte))]  
  }else {
    htetrain<-lapply(hte[grepl(i,names(hte))],addtraintest,z=i)
    names(htetrain)<-names(hte)[grepl(i,names(hte))]
    hte2<-c(htetest,htetrain)
  }
  }
rm(hte,htetest,htetrain)
names(hte2)[grepl("/y_",names(hte2))]<-gsub("/y_","y_",names(hte2)[grepl("/y_",names(hte2))])

```

##Combine train and test sets 

```{r a, echo=FALSE}
namesroots<-gsub("test","",names(hte2)[grepl("test",names(hte2))])

#i<-namesroots[1]
for (i in namesroots) {
if (i==namesroots[1]) {
  htetraintest<-list(rbind(hte2[[paste(i,"test",sep="")]],hte2[[paste(i,"train",sep="")]]))
} else {  htetraintest[[length(htetraintest)+1]]<-rbind(hte2[[paste(i,"test",sep="")]],hte2[[paste(i,"train",sep="")]])
}
names(htetraintest)[which(namesroots==i)]<-namesroots[which(namesroots==i)]
}

```

